### ISSUE TITLE
Page sheet Modal Flickering

### ISSUE THREAD

**Issue by Dwar3xwar** [grahammendick/navigation#523] opened 2021-06-22 22:49 UTC
Hey @grahammendick, hope you are well. 

Running into an issue with the `Modal` object for  the `pageSheet` configuration. Looks like there is an issue with the rendering of the `Modal` when pulling down.

This seems to be a known issue as shown in another navigation library here: https://github.com/software-mansion/react-native-screens/issues/577

I was trying to reproduce this issue in one the `sample` projects, but I am having issues running them at the moment, so advice would be appreciated on how run them 😄 

Attached is a video of this using the `Modal`

**"WARNING: This video may potentially trigger seizures for people with photosensitive epilepsy. Viewer discretion is advised."**

https://user-images.githubusercontent.com/12078810/123009077-0ce1bc00-d38a-11eb-91fd-7ba2c5e0c743.mov

**Comment by grahammendick** [comment] 2021-06-23 17:44
Hey, I'm good thanks and nice to hear from you again.

The React Native Modal doesn't support pull/swipe to dismiss yet. A while back, React Native [changed their Modal to support it](https://github.com/facebook/react-native/commit/6d00239e4970354ad4dc39e1c0f9099da6ea11e8). But they found a problem with it and backed it out and it’s not been fixed since (despite there being lots of issues and PRs on React Native about it)!

Can you try `pageSheet` outside of the Navigation router, using just React Native, and see if you have the same problem. please?

**Comment by Dwar3xwar** [comment] 2021-06-24 20:57
@grahammendick 

The issue seems to be resolved when taken out of the Navigation router!

**Comment by grahammendick** [comment] 2021-06-25 15:46
I tried setting the `presentationStyle` to `pageSheet` [in the Medley sample](https://github.com/grahammendick/navigation/blob/857d8b619543e9ad081f6351a990a2a8243213b2/NavigationReactNative/sample/medley/Direction.js#L61) and it works fine. 

https://user-images.githubusercontent.com/1761227/123450134-4c034d80-d5d4-11eb-8998-7d9af964f1de.mov

You should try out the Medley sample so you can see what I mean. You said you were having trouble getting the samples running. Could you tell me what went wrong, please?

**Comment by Dwar3xwar** [comment] 2021-06-25 17:07
Hey, the issues running the sample projects are on my end and have been resolved!

I ran the `medley` project and it seems to not being causing an issue with the `pageSheet` modal. I wonder if the `Modal` being  within the `NavigationHandler` is the source of the issue.

**Comment by grahammendick** [comment] 2021-06-25 17:18
Glad you've got the samples running and you can see the Navigation router works with pageSheet Modal.

**Comment by grahammendick** [comment] 2021-06-25 17:20
I'm guessing it must be some other library that's causing the problem. Perhaps you could try removing other libraries to isolate the cause?

**Comment by grahammendick** [comment] 2021-06-25 17:24
I recall you work with @salockhart , right? I suggested that he try a patch to get swipe to dismiss working. Perhaps that could be causing the problem

**Comment by Dwar3xwar** [comment] 2021-06-28 14:35
@grahammendick Yes I do. I'll connect with him on our next steps. Thanks for everything!

**Comment by grahammendick** [comment] 2021-07-12 11:06
@Dwar3xwar @salockhart You Ok if I close this?

**Comment by salockhart** [comment] 2021-07-12 11:11
Hi @grahammendick yes apologies this got de-prioritised on our end. We may revisit this in the future, but until then this is fine to close.

**Comment by grahammendick** [comment] 2021-07-12 11:14
No problem. Please let me know if you find out anything

**Closed by grahammendick** 2021-07-12 11:14 UTC
