### ISSUE TITLE
Expo AV play blank Screen

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#807] opened 2024-09-19 20:38 UTC
Hi, Am The navigtion router with Expo AV and its working very very well. However when i navigate back after watching a video and navigate to watch the video again i get a blank screen. I did a search on expo AV documentation to use video.current.unloadAsync() to clean up in useEffect but i still get the blank screen.  When i restart the app and play the video it works perfect. Is there a way i can rerender when i navigate back in The navigation router? Thanks

**Comment by grahammendick** [comment] 2024-09-19 21:37
Hi, have you tried debugging it inside xcode or android studio? That's usually a good starting point. Maybe you see what the difference is with the player when it's working and when it isn't?

**Comment by salisuabubakar** [comment] 2024-09-20 09:31
Hello, thanks for your response. I have done that and its still the same. Is it possible to remove a screen from the stack when you navigate. I think it will help when am able to that because when i close the app and launch it agan it works perfectly.

Thanks

**Comment by grahammendick** [comment] 2024-09-20 09:55
Could you explain more about what scene the video is on and the navigation that's happening, please? It wasn't clear to me from your description. For example, are you navigating from A to B and then back to A? Is the video on scene A or scene B? Does this happen only on Android or iOS or is it on both?

**Comment by salisuabubakar** [comment] 2024-09-20 10:37
Ok thanks for the quick response. I have a button on Scene A and when i click the button it takes me to Scene B where the video is displayed. Because of the blank screen thst i get i would like to remove the scene B from the stack when i navigate back to Scene A. Hope its clear. Thanks for your time

**Comment by grahammendick** [comment] 2024-09-20 10:45
The Navigation router does remove scene B from the stack when you navigate back to Scene A

**Comment by salisuabubakar** [comment] 2024-09-20 10:53
Ok thanks. Is there any solution you would like to suggest ? Thanks

**Comment by grahammendick** [comment] 2024-09-20 10:58
You have to do some debugging to work out where the problem is. You should create a brand new project with just the Navigation router and Expo AV dependencies and nothing else. Then test the same scenario of navigating from A to B and back again and see if the problem happens. If it doesn't then it's a problem with your code.

**Comment by grahammendick** [comment] 2024-09-28 14:01
Hey, here's an [example using react-native-video](https://github.com/TheWidlarzGroup/react-native-video) that shows the video plays great after navigating back and then forward again (I tried to use expo-av but couldn't get expo modules working). The vid below shows iOS but I checked it works on Android as well. I've included the full working code below. I suggest you use the code below to try it out with expo-av. I'm closing this but if the code below doesn't work with expo-av could you upload the project to github and I'll take a look, thanks.

https://github.com/user-attachments/assets/fa610658-b710-482e-8217-46694a4b0d81

```jsx
/* eslint-disable react-native/no-inline-styles */
import React, {useContext, useRef} from 'react';
import {Text, View, TouchableHighlight} from 'react-native';
import Video, {VideoRef} from 'react-native-video';
import {StateNavigator} from 'navigation';
import {NavigationHandler, NavigationContext} from 'navigation-react';
import {NavigationStack, Scene} from 'navigation-react-native';

const navigator = new StateNavigator([
  {key: 'hello'},
  {key: 'player', trackCrumbTrail: true},
]);

const Welcome = () => {
  const {stateNavigator} = useContext(NavigationContext);
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <TouchableHighlight
        underlayColor="blue"
        style={{backgroundColor: 'blue', width: 200, height: 70, alignItems: 'center', flexDirection: 'row',justifyContent: 'center'}}
        onPress={() => {
          stateNavigator.navigate('player');
        }}>
        <Text style={{color: 'white', fontSize: 20}}>Play</Text>
      </TouchableHighlight>
    </View>
  );
};

const Player = () => {
  const videoRef = useRef<VideoRef>(null);
  return (
    <Video
      source={{uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'}}
      ref={videoRef}
      style={{position: 'absolute', top: 0, left: 0, bottom: 0, right: 0}}
      paused={false}
    />
  );
};

const App = () => (
  <NavigationHandler stateNavigator={navigator}>
    <NavigationStack>
      <Scene stateKey="hello">
        <Welcome />
      </Scene>
      <Scene stateKey="player">
        <Player />
      </Scene>
    </NavigationStack>
  </NavigationHandler>
);

export default App;
```

**Closed by grahammendick** 2024-09-28 14:01 UTC

**Comment by salisuabubakar** [comment] 2024-09-28 20:38
Yes react native video is working perfectly. I think there are some issues with expo-av. Thanks soo much.
