### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#347] opened 2020-01-11 14:49 UTC
Sometimes the app crashes when brought to the foreground after being too long in the background.

![WhatsApp Image 2020-01-11 at 21 42 52](https://user-images.githubusercontent.com/25284201/72206052-28ba1080-34bc-11ea-90da-237e5a66ea42.jpeg)

**Comment by grahammendick** [comment] 2020-01-11 23:18
This is a duplicate of #314.  The issue gives a workaround and the details of an investigation, Give it a read and let me know if you're interested in taking up the investigation

**Comment by grahammendick** [comment] 2020-01-15 16:06
I'm closing this but if you're interested in taking up the investigation let me know and we can re-open #314

**Closed by grahammendick** 2020-01-15 16:06 UTC

**Comment by grahammendick** [comment] 2020-06-01 17:36
I've [done the investigation in #314](https://github.com/grahammendick/navigation/issues/314#issuecomment-637004821) and the app state is restored automatically.
